### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by PackageInstaller** [Amber-siley/nonebot-plugin-EnjoyAnimation#3]
系统：6.3.1-arch2-1
Bot：zhunxun_bot(基于nonoebot)

使用**番剧更新**指令后会在机器人根目录下保存番剧封面图，看起来很乱，不知道是不是我插件结构问题，如下图

![image](https://github.com/small-bili/nonebot-plugin-EnjoyAnimation/assets/80018096/f8beb86c-06a5-4bbd-b339-ad6a3d6fe4c8)

插件结构如图
![Screenshot_20230511_205659](https://github.com/small-bili/nonebot-plugin-EnjoyAnimation/assets/80018096/c2d2864e-d1b9-45f5-a390-9866095578a7)

建议直接放data目录下对应文件夹会更好？

**Comment by PackageInstaller** [comment]
另外，已经在.env.dev里面填写了管理员账号，但是订阅番剧时还是提示无管理员权限
![image](https://github.com/small-bili/nonebot-plugin-EnjoyAnimation/assets/80018096/83ca581d-7ea4-49ee-9ddc-89396ca15e61)

**Comment by Amber-siley** [comment]
图片本来应该存放到pic文件夹的，之后会考虑放在data目录下的，是Linux系统嘛，Linux系统我还没有测试过

**Comment by PackageInstaller** [comment]
是linux系统

**Comment by Amber-siley** [comment]
0.0.4修复好了，需要调整的地方我写到readme中的ps了

**Comment by Amber-siley** [comment]
根目录下的图片也可以删除了，我将所有的配置文件放在data目录下了
