### ISSUE TITLE
插件加载报错

### ISSUE THREAD

**Issue by PackageInstaller** [Amber-siley/nonebot-plugin-EnjoyAnimation#4]
![image](https://github.com/small-bili/nonebot-plugin-EnjoyAnimation/assets/80018096/2b83dc54-a45c-427c-be8f-35889fa50701)
加载时出现这个报错，所有指令都无法使用了

**Comment by PackageInstaller** [comment]
OS：Arch Linux
Bot：zhenxun_bot
Python：3.11.3
nonebot：2.0.0rc4

**Comment by Amber-siley** [comment]
json文件加载出错了，你看看animation.json文件是不是在data路径下，或者animation.json文件里面内容是不是损坏了，是不是在多个用户使用下才出现的这个问题？

**Comment by PackageInstaller** [comment]
看了一下，里面是空的，需要删除让他重新生成吗

**Comment by Amber-siley** [comment]
嗯嗯，删除了重新生成，没生成成功的话，可能是信息来源网站更新，

**Comment by PackageInstaller** [comment]
自动生成了，但是还是空的，用番剧更新指令也没反应

**Comment by Amber-siley** [comment]
emmm，网站更新了，这个插件目前就先别使用了，我过两天看看情况，因为最近在忙期末

**Comment by Amber-siley** [comment]
我试了一下，你的插件版本是多少，最新的嘛？

**Comment by PackageInstaller** [comment]
Yep

**Comment by Amber-siley** [comment]
试了一下只有0.0.3版本才有这个问题，你试试pip show EnjoyAnimation看看版本version是不是0.0.4，0.4版本在Ubuntu运行没有问题，如果版本不是0.4版本，尝试readme ps中的进行更新插件，因为镜像源没有更新，所以用镜像源更新的话可能还是0.3版本，readme中有官方源更新的指令

**Comment by Amber-siley** [comment]
记得删除Animation.json文件，不管是根目录下的，还是data目录下的，具体参考ps

**Comment by PackageInstaller** [comment]
![image](https://github.com/small-bili/nonebot-plugin-EnjoyAnimation/assets/80018096/2c735f62-59bf-4105-823f-9c70eca0166b)
是最新版的，删除后自动创建的还是空的，并且报错与最上面的一样

**Comment by Amber-siley** [comment]
是不是网络问题，尝试访问https://yuc.wiki/202304/这个网页看看能不能访问

**Comment by PackageInstaller** [comment]
emmmm,确实是网络问题，日本节点打不开

**Comment by PackageInstaller** [comment]
尴尬了，那我先close了

**Comment by Amber-siley** [comment]
没有其他问题就先close了
